# Generated by Django 5.2.7 on 2025-10-14 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_image_order_orderbouquet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbouquet',
            name='bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.bouquet'),
        ),
    ]
