# Generated by Django 5.2.7 on 2025-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_orderbouquet_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbouquet',
            name='bouquet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
